### ISSUE TITLE
Documentation display and link issues

### ISSUE THREAD

**Issue by n0rd1c** [homarr-labs/documentation#39]
### Environment

Docker

### Version

0.15.0

### Describe the problem

when i browse to this url:  https://homarr.dev/docs/management/integrations/  i noticed that the headings seem to be not in the right place.  

![image](https://github.com/homarr-labs/documentation/assets/47068441/89fa2d4a-d62b-4c6a-b4a9-61dd1f8a2f08)

also when i click the bottom two integrations, i get a page not found error.

![image](https://github.com/homarr-labs/documentation/assets/47068441/490142c5-9de3-4664-952f-8243900bef23)

### Please tick the boxes

- [X] You've read the [docs](https://github.com/ajnart/homarr#readme)
- [X] You've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
- [X] You've tried to debug yourself

**Comment by manuel-rw** [comment]
Should get solved by #38

**Comment by ajnart** [comment]
Got solved by #38
